//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public string admin_email { get; set; }
        public string password { get; set; }
        public string nombre_municipalidad { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
