//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupacion_Usuario
    {
        public string nombre_agrupacion { get; set; }
        public string nombre_municipalidad_agrupacion { get; set; }
        public string usuario_email { get; set; }
        public string nombre_municipalidad_usuario { get; set; }
        public bool admin { get; set; }
    
        public virtual Agrupacion AGRUPACIONES { get; set; }
        public virtual Usuario USUARIOS { get; set; }
    }
}
