//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cerebroDBEntities : DbContext
    {
        public cerebroDBEntities()
            : base("name=cerebroDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIONES> ACCIONES { get; set; }
        public virtual DbSet<AGRUPACIONES> AGRUPACIONES { get; set; }
        public virtual DbSet<AGRUPACIONES_USUARIOS> AGRUPACIONES_USUARIOS { get; set; }
        public virtual DbSet<EVENTOS> EVENTOS { get; set; }
        public virtual DbSet<EVENTOS_FUENTES_DE_DATOS> EVENTOS_FUENTES_DE_DATOS { get; set; }
        public virtual DbSet<FUENTES_DE_DATOS> FUENTES_DE_DATOS { get; set; }
        public virtual DbSet<MUNICIPALIDADES> MUNICIPALIDADES { get; set; }
        public virtual DbSet<TIPOS_DE_FUENTES_DE_DATOS> TIPOS_DE_FUENTES_DE_DATOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
