//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS_FUENTES_DE_DATOS
    {
        public string nombre_evento { get; set; }
        public string nombre_municipalidad_evento { get; set; }
        public int id_fuente_de_datos { get; set; }
        public string nombre_municipalidad_fuente_de_datos { get; set; }
        public string umbral { get; set; }
    
        public virtual EVENTOS EVENTOS { get; set; }
        public virtual FUENTES_DE_DATOS FUENTES_DE_DATOS { get; set; }
    }
}
