//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUENTES_DE_DATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUENTES_DE_DATOS()
        {
            this.EVENTOS_FUENTES_DE_DATOS = new HashSet<EVENTOS_FUENTES_DE_DATOS>();
        }
    
        public int id { get; set; }
        public string ubicacion { get; set; }
        public string dirIP { get; set; }
        public string user_agent { get; set; }
        public string nombre_municipalidad { get; set; }
        public string nombre_tipo_de_fuente_de_datos { get; set; }
        public string nombre_municipalidad_tipo_de_fuente_de_datos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTOS_FUENTES_DE_DATOS> EVENTOS_FUENTES_DE_DATOS { get; set; }
        public virtual MUNICIPALIDADES MUNICIPALIDADES { get; set; }
        public virtual TIPOS_DE_FUENTES_DE_DATOS TIPOS_DE_FUENTES_DE_DATOS { get; set; }
    }
}
