//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOCAR_WS
    {
        public string nombre_evento { get; set; }
        public string nombre_municipalidad_evento { get; set; }
        public string url_web_service { get; set; }
        public string parametros { get; set; }
        public string metodo { get; set; }
    
        public virtual ACCIONES ACCIONES { get; set; }
    }
}
