//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_DE_FUENTES_DE_DATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOS_DE_FUENTES_DE_DATOS()
        {
            this.FUENTES_DE_DATOS = new HashSet<FUENTES_DE_DATOS>();
        }
    
        public string nombre { get; set; }
        public int frecuencia_de_lectura { get; set; }
        public string tipo { get; set; }
        public string url_web_service { get; set; }
        public string nombre_municipalidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUENTES_DE_DATOS> FUENTES_DE_DATOS { get; set; }
        public virtual MUNICIPALIDADES MUNICIPALIDADES { get; set; }
    }
}
