//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerebro_DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.AGRUPACIONES_USUARIOS = new HashSet<AGRUPACIONES_USUARIOS>();
        }
    
        public string email { get; set; }
        public string nombre_municipalidad { get; set; }
        public string nombre { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGRUPACIONES_USUARIOS> AGRUPACIONES_USUARIOS { get; set; }
        public virtual MUNICIPALIDADES MUNICIPALIDADES { get; set; }
        public virtual OPERADORES OPERADORES { get; set; }
        public virtual VISITANTES VISITANTES { get; set; }
    }
}
